### ISSUE TITLE
Build crashes because font-awesome can't find the bower target

### ISSUE THREAD

**Issue by FilmKnurd** [cbroeren/ember-context-menu#15]
I tried to upgrade to 0.1.3, but I'm running into martndemus/ember-font-awesome#109

**Comment by cbroeren** [comment]
I'm taking a look into this right now. Trying to fix it without removing font-awesome like #16

**Comment by cbroeren** [comment]
See #19 (temporary removed the font-awesome support, since the ember-font-awesome addon isn't updated recently and doesn't look like it will be
