### ISSUE TITLE
Add font-awesome functionality back

### ISSUE THREAD

**Issue by orf** [cbroeren/ember-context-menu#27]
Hey,
`ember-font-awesome` has been updated recently and no longer has any bower dependencies, `font-awesome` is installed via npm.

Was the bower dependency the reason `font-awesome` functionality was removed? If so could it be re-enabled?

**Comment by cbroeren** [comment]
The bower dependency wasn't the reason it was enabled. It wasn't working with some newer dependencies we've updated lately. 

I've seen it is updated recently, so I wanted to implement it again when I have the time for this. Currently I'm really busy, wanna try to re-implement it this week.

**Comment by cbroeren** [comment]
Or anyone who wants to fix this, can create a PR by bringing everything back as it was:
[See this commit where I removed it](https://github.com/cbroeren/ember-context-menu/pull/19/commits/dac984d32bfe7d3f4bef4bc6ad3dd3e2482f5da7)

**Comment by cbroeren** [comment]
See #28

**Comment by cbroeren** [comment]
Published 0.3.2
