### ISSUE TITLE
Icon Error

### ISSUE THREAD

**Issue by nelnico** [cbroeren/ember-context-menu#31]
When specifying an icon for a menu item I get an error "Error: Compile Error: fa-icon is not a helper"

I did "ember install ember-font-awesome" without any luck

**Comment by wuarmin** [comment]
I have the same issue.

**Comment by nelnico** [comment]
I tried making it a dependency, devdependency, and not sure what else.
Ended up removing the addon and linking to fontawesome cdn directly.  (temporary solution, but it works for now)

**Comment by rwwagner90** [comment]
I believe this is no longer an issue, as it worked for me. If anyone is still experiencing issues, please let us know.
