### ISSUE TITLE
menu does not display

### ISSUE THREAD

**Issue by jnkroeker** [cbroeren/ember-context-menu#37]
Hey there,

I am able to catch the right click event on my component in _contextMenu(e){ } but it appears that my contextItems array is not found. Should the label attribute of each object in contextItems be displayed as a menu item without further configuration? Thanks for this add-on!

**Comment by jnkroeker** [comment]
Solved this by overriding default z-index css attribute on wormhole-context-menu element from 100 to 1000

**Comment by cbroeren** [comment]
Hi John,
I'm sorry I wasn't able to respond until now. I'm glad you've found a solution already. Let me know when you have other problems or questions on using it.

**Comment by jnkroeker** [comment]
Hi Chantal,
I do have another question. I am having trouble registering my context menu item actions to their click event. Something as simple as the following I am not seeing write to console. Can you explain how onClick actions are bound and what I might be doing wrong?

contextItems: [
    {
      label: 'Add wave',
      icon: 'plus',
      action(){
        console.log('in here!');
      }
  ]

**Comment by cbroeren** [comment]
I can't see doing something wrong. This is exactly how easy it should work. Did you try it in your tests, or in the application itself. We're having problems triggering the actions on clicking the items inside tests.

**Comment by jnkroeker** [comment]
I spoke to my colleagues and they showed me that the root element of the app in question had been configured as something other than index.html body. This was causing a problem with the wormhole. I reset the root to body and your addon is working great. Thanks again for a great add-on.
