### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by jrode** [cbroeren/ember-context-menu#4]
To get this working I had to:
```
ember install ember-wormhole
ember install ember-invoke-action
```

Perhaps these two should be in `"dependencies"` instead of `"devDependencies"`?

**Comment by cbroeren** [comment]
@jrode, I'm sorry, didn't get any github notifications of this issue. Will take a look at this in the next 2 days to fix it

**Comment by jrode** [comment]
No problem. The context menus are working great for the record, nice work.

**Comment by cbroeren** [comment]
Fixed this. Will be released in the next version

**Comment by jrode** [comment]
Excellent, thanks very much!
