### ISSUE TITLE
New release / npm permissions

### ISSUE THREAD

**Issue by rwwagner90** [cbroeren/ember-context-menu#47]
Hi @cbroeren, would you be able to give me npm permissions so I can help with releases?

**Comment by cbroeren** [comment]
Sure! What's your npm username?

**Comment by rwwagner90** [comment]
@cbroeren I am rwwagner90 everywhere, thanks!

**Comment by cbroeren** [comment]
@rwwagner90 done!

**Comment by rwwagner90** [comment]
Thanks for releasing @cbroeren! I don't think I have npm permissions yet though.

**Comment by cbroeren** [comment]
I've sent the invite earlier today, but seems like something went wrong. Just tried again and you're on the maintainer list now. Could you check again?

**Comment by rwwagner90** [comment]
I think it worked now. Thanks!
